server:
  port : 8080
spring:
#  datasource:
##    url: jdbc:mysql://localhost:3306/todoapp?serverTimezone=UTC
#    url: jdbc:mysql://122.112.234.17:3306/todoapp?serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
     mongodb:
       host: localhost
       port: 27017
       username: user
       password: "123456"
       database: test
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

  jpa:
#    generate-ddl: true
#    database: MONGODB
    show-sql: true
logging:
  level:
    root: debug
